### ISSUE TITLE
Can you explain how buffer size affects performance?

### ISSUE THREAD

**Issue by null-python** [bailey27/cppcryptfs#110]
I don't really understand advantages/disadvantages of having a small vs large buffer size.

**Comment by bailey27** [comment]
cppcryptfs/gocryptfs store data in blocks of up to 4KB.  If a file is less than 4KB in size, then the one block can be less than 4KB. If the file is greater than 4KB in size, then every block except possibly the last one will be 4KB.

4KB is not the optimal i/o size for most systems.  It is too small.

So I made cppcryptfs, when it is asked to read or write more than 4 kilobytes, to buffer the data in memory and do the i/o in larger chunks.

I've found the sweet spot for how much to buffer to be either 64KB or 128KB.  Making it larger than 128KB doesn't really help that much, and 64KB is almost as fast as 128KB if the backing store is an SSD.

Too large of a buffer size can be sub-optimal if the backing store is a network drive.

Because 64KB seems to be optimal for network drives and reasonably fast for local drives, I made 64KB the default.

Here are some examples of local SSD performance.

My ssd is very old, and not particularly fast.  

SSD with native write speed of 350MB/sec.  CPU is i5-4200U 

|I/O buffer size|Write speed writing 1MB at a time|
|---|---|
| 4 KB|113 MB/sec|
|64 KB|229 MB/sec|
|128 KB|253 MB/sec|
|1024 KB|258 MB/sec|

**Comment by null-python** [comment]
thanks for the info
