### ISSUE TITLE
"Time out" error when simultaneous mountings launched from CMD command line

### ISSUE THREAD

**Issue by Freeedim** [bailey27/cppcryptfs#112]
Hi there,

Thanks for cppcryptfs, which is a great tool I have been happily using for 18 months now.

This is a minor issue that may however be a symptom for some deeper problem.

I had not made any update since v1.4.0.26 and have just updated to v1.4.3.2 and noticed my script did not work any more.

My CMD script mainly consists of a FOR loop that mounts all my volumes with a cppcryptfs's command (with passwords read from a file). To avoid wasting time (there are around 20 volumes), every cppcryptfs command would itself be launched by a "START" command to have a dedicated process for each volume mounting.

With the newer version, this does not work any longer. The first volume is being correctly mounted but then all the others throw a "time out" error message as soon as they start.

It seems the mounting speed has been greatly improved from the former version to the newer, so I have just dropped the "START" command and I am letting cppcryptfs mount my volumes sequentially at barely any time cost. But I think this new behaviour might indicate something wrong in the concurrent processes management.

Thanks for your attention.

**Comment by bailey27** [comment]
Thanks for reporting this.

cppcryptfs, when used to send arguments to a running instance of itself, used to use Windows messages for communication.

A while ago I changed it use a named pipe instead.  

If a 2nd instance tries to connect to the named pipe while another instance is connected and communicating (e.g. waiting for a mount operation to complete), then it waits for only 2 seconds on the named pipe connection before timing out.

Two seconds isn't long enough for a mount operation to complete.  So it times out and returns a error.  I don't know why I made the timeout so short.

I will change it to wait forever if the named pipe connection is busy.

BTW, have you looked at cppcryptfsctl?  It's a console mode program so it can have its output redirected, and it sets errorlevel properly.  I think it's better for using in batch files.

**Comment by Freeedim** [comment]
Thanks for your quick and very clear answer.

But if I understand well, in any case (even with my former version), it is useless to create many different parallel processes with the command "START" in my FOR loop because anyway, each mounting operation will wait for the running instance to finish the previous mount, right? (However, I think I had noticed better performance with parallel mounting with the former version).

I have seen cppcryptfsctl arriving in the changelog trail, but I haven't taken time to get familiar with it yet. I know nothing about CMD/Batch except the very minimum I had to learn to automatise cppcryptfs mounting of a batch of volumes... Did you mean that cppcryptfsctl  would allow to have detailed logs in a file in order to better figure out what causes an issue?

**Comment by bailey27** [comment]
Yes, cppcryptfs mounts the volumes sequentially.  It waits for Dokany to signal it whether the drive mounted successfully or not.

I would like to make this process asynchronous so you could kick off several mount operations at the same time.

I've noticed that the drive becomes useable almost instantly after you click "Mount" but it takes about 5 seconds for Dokany to signal success on my machine.  Maybe the signal from Dokany is coming faster than before on your machine?

I looked at using WM_DEVICECHANGE for getting confirmation of a mount because I thought it could come faster than from Dokany.  But for reasons I don't understand, I get this message only when I unmount a cppcryptfs volume. I do get it both when I insert and eject a usb drive, though.  I'm using it now just for keeping track of which drive letters are available for mounting.

I could still make mounting asynchronous though.

cppcryptfsctl is there to replace cppcryptfs itself for command line usage.  It really doesn't matter which one you use if it either works for you.

**Comment by bailey27** [comment]
I just tried polling whether the root of the mounted fs exists in addition to waiting on the Mounted signal from Dokany.  

By signal, I mean I'm waiting on an event that that I set to signaled when Dokany calls me back in another thread indicating mounted succeeded or failed.

Now, instead of only waiting on Dokany to call back,  I have a loop that checks if the root of the fs exists, and if not then waits on the signal for up to 1/10th second and then checks if the path exists again. Once 30 seconds have gone by without success or failure, it times out.

This results in almost instantaneous mounting, and I think it makes asynchronous mounting unnecessary.

**Comment by bailey27** [comment]
Now I'm also getting the WM_DEVICEDCHANGE message when I mount the volume.  I guess before, because I was stuck waiting for Dokany for five seconds, Windows didn't send the message because my app took too long to get back to waiting on windows messages.  I would have thought Windows should go ahead and post the message regardless if my app was capable of receiving it right away.

**Comment by bailey27** [comment]
There's a new version up with the fix for the timeout on the named pipe.

https://github.com/bailey27/cppcryptfs/releases/tag/1.4.3.4

It also has an "Enable fast mounting" setting which is enabled by default.

With this setting on, I'm getting a successful indication of mounting in about 31 milliseconds instead of 5 seconds as before.

**Comment by eugenesvk** [comment]
@bailey27 I think that might also be the reason behind my issue #79 and explains the interesting quirks I've discovered recently (https://github.com/bailey27/cppcryptfs/issues/79#issuecomment-724790002) because with this new version I get a responsive tray icon right away and if I close the console right away, the app doesn't quit (it might've needed the console to stay open due to that messaging stuff)
Will keep an eye whether any of the issues still pop up in the future, but hopefully I'll finally be able to reliable automount the encrypted drive on login.

**Comment by Freeedim** [comment]
Great! Thanks again for your swift and effective reaction.
