### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by midshipmanorg** [bailey27/cppcryptfs#113]
No issue at all - but a big THANK YOU for providing the public with one of the best cryptographic tools available.

**Comment by bailey27** [comment]
Wow!  That makes me feel really good.

**Comment by encedo** [comment]
Hi Bailey, 

I'm going to join the colleague - BIG THANKS. And indeed this is one of the best tools to secure files on the market. I'm using it since early 1.3 version after switching from TrueCrypt clones. With Nextcloud to sync root folder, this is my tandem to secure cloud files.

I can help you with code singing. I have an EV certificate required to satisfy Microsoft SmartScreen Filter. I can cross-sign your executable and make them public. My signature will be added to yours. Check this out: https://cloud.encedo.com/s/4qALpsxMSb7S54T . 

What do you think?

I have even more plans about this tool, let's talk directly.

Chris

**Comment by bailey27** [comment]
@encedo , thanks for the offer to cross-sign.

I think it doesn't help though, at least not for me.  I downloaded your .exe, and even though I could see your EV signature, I still got the smart screen anway.

![image](https://user-images.githubusercontent.com/17813578/103245896-978fb400-492f-11eb-9552-7dbfefa511e1.png)

![image](https://user-images.githubusercontent.com/17813578/103245907-9e1e2b80-492f-11eb-9687-e30ea9ff4be2.png)

I am not sure why.  Maybe MS doesn't like the fact that it's also signed with my cheap open source developer cert?

I'm not sure if I'd want to release without my own signature there, though.

I sent you a connect request on linkedin.

I'm seriously considering supporting WinFSP in addition to Dokany.  I think the performance will be better with WinFSP. I think I could make it dynamically use whichever one is available and have a setting to prefer one over the other if both are installed.

**Comment by encedo** [comment]
Hi Bailey,

yes, there is an issue with such a cross-signing. Looks like Windows checks the first signature. Testes on fresh Windows VMs from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/. No Smart Screen warnings, no Edge warnings. All works correctly. Here is a version of the app signed by my cert only: https://cloud.encedo.com/s/aaipXsXd6re6AFX . My offer to release the ap signed by my cert is open - we can handle it in many ways.

WinFSP looks very promising, especially by the performance! If the porting is not that difficult, consider autodetection (with WinFSP as the first choice).

Chris

**Comment by bailey27** [comment]
Chris,

I didn't know MS had those dev vms.  Thanks for the tip!  I used it to test this.

I verified that if I sign after you, that SmartScreen doesn't warn in that case. I did this with files I uploaded from my pc and downloaded in the vm from github (in a zip attachment to an issue). 

I found a tool that removes signatures, so I can make sure the sha256 of of the unsigned .exe doesn't change.  I made sure this process works.  I apologize for the paranoia, but I feel I must do this.

So if you want, and at your leisure, please download the .exe's from the latest release and sign them replacing my signature with yours and zip them up and attach the zip to an issue.  I can download them and verify the sha256's and add my signature and replace the files on the release page with the dual-signed ones and remove the stuff about the SmartScreen warnings from that release.

Thanks for coming up with this idea and offering to do this.

Bailey

**Comment by encedo** [comment]
Hi Bailey,

the files signed by my EV are here: https://cloud.encedo.com/s/dk83zpyQdKBP6ws . Sorry, I have no clue how to attach ZIP file here on Github :/  Hmm....

Chris

**Comment by encedo** [comment]
One more thing...

Microsoft VMs are great for testing. Consider adding a guide on how to build cppcryptfs using those VMs. I haven't check it but from my experience compiling under Windows is not a hassle-free process :/

**Comment by bailey27** [comment]
Chris,

I signed your executables and uploaded them on the releases page.

I tested in a fresh VM, and there was no SmartScreen warning.

Thanks again so much for doing this.

If you drag a .zip into a github comment, it attaches the file.  I had to google for that.  I expected something in the toolbar to do it.

The build instructions are here

https://github.com/bailey27/cppcryptfs/blob/master/INSTALL.md

I think the only difference with the VM is that because Visual Studio is already installed, you'd need install the the extra C++ tools and libraries afterwards instead of selecting them during installation.  

If you run the Visual Studio Installer app and select "Modify" you can add the needed tools.  Which ones you need are shown in https://github.com/bailey27/cppcryptfs/blob/master/INSTALL.md.  

If something doesn't work for you please let me know, and I can help and improve the instructions.

Bailey
