### ISSUE TITLE
Example of storing encrypted (reverse-mode) content on a cloud storage

### ISSUE THREAD

**Issue by ericvrp** [bailey27/cppcryptfs#119]
I am using reverse mode to create an encrypted view of my data. I created a mountpoint for this in my Dropbox folder but Dropbox is not  syncing the folder. I guess this is because it's a read-only folder.

What is the suggestion solution to get this usecase to work? I could not find it in the docs.

**Comment by bailey27** [comment]
I am sure the problem is the read-only thing. 

This has come up with gocryptfs before.  I think there were other discussions, but I was able to find only this one quickly.

https://github.com/rfjakob/gocryptfs/issues/345

If gocryptfs ever implemented read-write reverse mode, then, I would try to do it also.  But I think as long as gocryptfs doesn't do it, then I won't either.

Why are you doing it this way?  Personally, I just create a (forward) encrypted fs in my dropbox folder and mount that.
