### ISSUE TITLE
CrystalDiskMark speeds too fast?

### ISSUE THREAD

**Issue by null-python** [bailey27/cppcryptfs#130]
I was testing a mounted volume and the underlying drive as well and got these results

**Underlying drive**
[Read]
  SEQ    1MiB (Q=  1, T= 1):   177.103 MB/s [    168.9 IOPS] <  5911.35 us>
  RND    4KiB (Q=  1, T= 1):     0.914 MB/s [    223.1 IOPS] <  4462.75 us>

[Write]
  SEQ    1MiB (Q=  1, T= 1):   160.182 MB/s [    152.8 IOPS] <  6527.12 us>
  RND    4KiB (Q=  1, T= 1):     2.941 MB/s [    718.0 IOPS] <  1388.49 us>

Profile: Real
   Test: 128 MiB (x1) [D: 9% (167/1863GiB)]

**gocryptfs volume**
[Read]
  SEQ    1MiB (Q=  1, T= 1):   638.311 MB/s [    608.7 IOPS] <  1638.78 us>
  RND    4KiB (Q=  1, T= 1):    64.421 MB/s [  15727.8 IOPS] <    63.17 us>

[Write]
  SEQ    1MiB (Q=  1, T= 1):   629.546 MB/s [    600.4 IOPS] <  1662.65 us>
  RND    4KiB (Q=  1, T= 1):    59.797 MB/s [  14598.9 IOPS] <    68.10 us>

How is it possible for the encrypted volume to be more than 4 times faster?

**Comment by bailey27** [comment]
I think this is probably what's happening.

CrystalDiskMark is opening the files it's using for testing using FILE_FLAG_NO_BUFFERING.

Using this flag tells Windows to  not cache the data.

cppcryptfs cannot use this flag when it opens the encrypted files because if you use FILE_FLAG_NO_BUFFERING then you must do all reads and writes aligned on the sector size (either 512 bytes or sometimes a multiple of 512 bytes like 4096).  Because gocryptfs does not align the encrypted data on 512 byte boundaries, cppcryptfs must remove this flag before opening the file.

So if CrystalDiskMark opens a file with this flag and then reads from it or writes to it repeatedly, it thinks it is bypassing the system disk cache and measuring the uncached speed (the speed of the physical disk).  But with cppcryptfs in the middle, the reads and writes are really being cached and CrystalDiskMark is actually measuring the speed of the system cache minus the performance hit from having to do the encryption/decryption and the Dokany overhead.

**Comment by null-python** [comment]
thanks for the info
