### ISSUE TITLE
Start Error Username and Domain Name since 1.4.3.8

### ISSUE THREAD

**Issue by gitusercodes** [bailey27/cppcryptfs#132]
Since cppcryptfs 1.4.3.8 I get a error Popup Message after starting the Exe

**Unable to get username and domain name**

I downgraded to 1.4.3.7 and there the error does not occur.
I use the 64 Bit and the latest Dokany 1.5.0.3000

Any Fix?
![cppcryptfs](https://user-images.githubusercontent.com/87264123/125191893-020d9f00-e245-11eb-96c5-d66ed01ce327.jpg)

**Comment by bailey27** [comment]
If you're not using the "Deny other users" setting, then you can ignore this message box on startup. 

You also will probably have problems with using cppcryptfsctl  or cppcryptfs from the command line to communicate with an already-running instance of cppcryptfs (because it now decorates the name of the name pipe with the user and domain name).

I have no idea why it's failing to get the user and domain name on startup.  If you want, I could send you a build with some debugging code in it.

If you'd rather not bother, I can just wait until this happens somebody who wants to use the "Deny other users" setting and see if they want to help debug it.

If you don't mind saying, is there anything unusual about you setup?  Like maybe are you using some kind of single sign on thing that replaces the normal Windows logon?

I'll make the next release work around this failure and not display the message unless the "Deny other users" setting is enabled.

**Comment by gitusercodes** [comment]
Hi Bailey,

thank you for the fast answer. I do not use "Deny other users".
I changed with cppcryptfsctl.exe the password and had no message.
You can send me the debug version, and maybe it shows the error in an useable output.
Me setup is normal with no single sign or anything else

**Comment by bailey27** [comment]
cppcryptfsctl doesn't use the named pipe when you change the password with it.  It uses it if you do something like list mount points. e.g "cppcryptfsctl -l"

I build a cppcryptfs that will display in the message box the reason why getting the user name failed. 

Please try it and post a screen shot of the error message box.
[cppcryptfs_debug_getusername.zip](https://github.com/bailey27/cppcryptfs/files/6796850/cppcryptfs_debug_getusername.zip)

**Comment by bailey27** [comment]
Actually, I think cppcryptfsctl will work just fine if getting the user and domain names fail for it also.

**Comment by gitusercodes** [comment]
Here is the screenshot with the error message box
![error](https://user-images.githubusercontent.com/87264123/125196868-cc27e500-e25b-11eb-8236-998906069829.jpg)

**Comment by bailey27** [comment]
Thanks!  

That error is ERROR_INVALID_HANDLE.  

That 0xfff..fc handle is what I get from GetProcessToken() which is a pseudo-handle for the current process.  It should be impossible for it to be considered an invalid token.  I get the same value on my system for it, and it works.

I'll make a version that doesn't use the pseudo-token and uses the actual process token.

**Comment by bailey27** [comment]
Here is a version that doesn't sue the pseudo handle and uses the real handle.

Please try it.

[cppcryptfs_debug_getusername_open_tok.zip](https://github.com/bailey27/cppcryptfs/files/6797168/cppcryptfs_debug_getusername_open_tok.zip)

**Comment by gitusercodes** [comment]
New version works without an error message box
Thank you!

**Comment by bailey27** [comment]
Great!  Thanks for debugging this.

I'll use that method in the next release.  I'll also make it not complain if anything goes wrong with this unless you go to mount with the Deny other users setting enabled.

I didn't include cppcryptfsctl in the previous zip.  Here's another one with the companion cppcryptfsctl.

[cppcryptfs_debug_getusername_open_tok_w_ctl.zip](https://github.com/bailey27/cppcryptfs/files/6797199/cppcryptfs_debug_getusername_open_tok_w_ctl.zip)

**Comment by bailey27** [comment]
The latest release (1.4.3.10) should fix this.  It uses session id and not username to restrict access to other users.
