### ISSUE TITLE
Use of "Session ID" VS "Deny other users"

### ISSUE THREAD

**Issue by gilles007-** [bailey27/cppcryptfs#134]
Windows 10 Pro, 1909
build: 1.4.3.8 64bit
dokany: 1.5.0.3000

I'm using the program with the same user i'm logged in (no admin rights)
While using "Deny other users", i have 2 problems :
1/ any administrator can reset my password and start using my mounted drive with a runas command
2/ sometimes, i need to start a program with admin rights and i can't no more access the mounted drive

Is it possible to add a "Deny other session ID" setting ?
![sessionid](https://user-images.githubusercontent.com/4212960/126319250-41a0de07-1ae1-490e-a735-c865f2068a61.jpg)

If cppcryptfs is running in session ID 1, only programs with session ID 1 could access the mounted drive

**Comment by gilles007-** [comment]
An option to allow Session ID 0 could be added too, for services, antivirus...

**Comment by bailey27** [comment]
_1/ any administrator can reset my password and start using my mounted drive with a runas command_

The use-case I designed this for was that the person using cppcryptfs was the owner of the machine and the only person with admin rights.  This person might share the machine with others whom he or she did not want to be able to access a mounted encrypted volume. 

_2/ sometimes, i need to start a program with admin rights and i can't no more access the mounted drive_

This isn't happening to me.  My user has admin rights, and when I want to run something as administrator, I right-click and select "Run as administrator", and any program I run as admin this way can access the mounted fs.  I've confirmed that  cppcryptfs keeps getting my username when it does the check in this case.

Do you run the command as a different user when you run with admin rights, or do you just elevate the same user that started cppcryptfs?

Dokany does have a mount option (it's turned with mirror by the /c option) that makes the mount visible only to the current session.  It it seems to work, but he problem I found with it was that if you start mirror as administrator and use /c, then you must be administrator to see the mounted fs.  While I don't normally run cppcryptfs as administrator because I never have problems with GetFileSecurity/SetFileSecurity when not running it as administrator, I could see that others might want to run it as administrator and not have to run everything as administrator to access the fs.

The only thing I can find that I'm able to get from Dokany about who's trying to access the mounted FS is the token (I think the thread token) that is making the request, and it works only in CreateFile.  I can get the user and domain from the token.  I haven't been able to figure out how to get the id of the session that originated the request.

I agree using session id to allow/deny access would be better.  I'll keep looking into this.

**Comment by gilles007-** [comment]
/c is interesting but suffer same problem as "Deny other users" :
From a user cmd :
`mirror.exe /r C:\test /l m /c`
`[Mirror] Failed to add security privilege to process`
`        => GetFileSecurity/SetFileSecurity may not work properly`
`        => Please restart mirror sample with administrator rights to fix it`
For what i can see, all operations are normal, and others accounts/sessions can't access the volume M.
But from an administrator cmd (right click, run as administrator) :
`m:`
`The specified drive could not be found.`
I can't access files.
So /c is not the solution.

If you have the user and the domain from the token, you can compare it with the output provided by "query session" or "qwinsta" but i see these commands don't output the domain.

**Comment by bailey27** [comment]
I found how to get the SessionId of the user trying to access the FS  from the token I can get from Dokany.

The MS documentation says the API I'm using is supposed to work only in a Terminal Services environment, but I see it works in Windows 10 Home.

I think the "switch user" functionality in Widows 10 Home is probably based on Terminal Services so the API works, and they forgot to update the documentation.

I think this will be a better solution.  

I'll upload a test executable soon in case you'd like to try it.

**Comment by bailey27** [comment]
@gilles007- I've attached a test version that uses session id.

It has one setting that controls whether other sessions are denied access, and another setting that controls whether services (in session 0) are denied access.

Please try it if you have time and let me know what you think.
[cppcryptfs_1.4.3.9alpha.zip](https://github.com/bailey27/cppcryptfs/files/6874118/cppcryptfs_1.4.3.9alpha.zip)

**Comment by gilles007-** [comment]
Thank you @bailey27

1/ i can say the program works great so thank you !
Other accounts don't have access to my volume
And i can run some program with admin rights too.
I can grant/deny windows services access to my volume with the "Deny services" option.
(I tested it with a SSH server from http://www.kpym.com)
As I supposed, this option is mandatory because i have a problem with USBDLM (a Windows service that gives control over Windows' drive letter assignment for USB drives) : service can't start. I hope to find a solution for this problem.

2/ i see that you have removed the previous option "Deny other users", asked by @ezyuzin
I don't know which one is better for other users of cppcryptfs

**Comment by bailey27** [comment]
I think "Deny other sessions" and "Deny other users" accomplish the same purpose, and "Deny other sessions" does it better.

I think it would be confusing to have two different options that do almost the same thing.

One thing I'll need to point out in the docs is that either a user with "Act as part of the operating system" privileges or a service running in the local System account is able to create a token with an arbitrary session id and defeat this protection.

I haven't done a proof of concept of that, but it is documented by MS.

**Comment by gilles007-** [comment]
Yes, i know : i have seen some program running as a service and still interact with terminal/citrix session users.

Personally, "Deny other sessions" and "Deny services" suit me better.
If i want to share a volume, i can't still uncheck "Deny services" and use permissions to restrict access.

Could i ask you to make available these 2 settings in CLI ?
I'm running cppcryptfs from a batch and i see that some settings are not available.
Thank you.

**Comment by bailey27** [comment]
I guess you could want to share some mounts with everybody and restrict access to other ones.

The settings are global and stored in the registry.

A volume uses whatever settings are in effect when it is mounted and isn't affected by subsequent settings changes while it is mounted.

To mount different volumes using different settings, you'd have to change the settings, mount one, then change the settings again and mount the other one.

I guess I could expose these settings in the CLI.   If I wrote the values to the registry and then mounted, then that mounting would use those settings.   I think another command line switch to make it restore the previous setting values in the registry after mounting would be needed too.

**Comment by bailey27** [comment]
"Deny Other Sessions" and "Deny Services"  has been released in 1.4.3.9.

Command line flags have been added for mounting with these options.  They don't affect the persistent settings you can set in the settings dialog.  They command line flags override those settings if they are specified.

**Comment by bailey27** [comment]
@gilles007- also, I changed the name of the registry value from DenyOtherUsers to DenyOtherSessions, so you'll need to re-check it in settings to turn it on again there.
