### ISSUE TITLE
Feature request: Dokany alternative

### ISSUE THREAD

**Issue by vampywiz17** [bailey27/cppcryptfs#14]
Hello there,

I found a good alternative to Dokany. It is much faster and more stable:

https://github.com/billziss-gh/winfsp

Performance test:

https://github.com/billziss-gh/winfsp/blob/master/doc/WinFsp-Performance-Testing.asciidoc

**Comment by bailey27** [comment]
Hi.

Thanks for telling me about WinFsp. 

In my tests it seems to be more than twice as fast as Dokany.

WinFsp  does have problems with winfstest https://github.com/dimov-cz/winfstest

It fails several tests and then winfstest seems to crash.

I think Dokany is pretty good.  I think maybe it would be better to find out why Dokany is slower and fix Dokany.

**Comment by billziss-gh** [comment]
@bailey27 I am the author of both [WinFsp](https://github.com/billziss-gh/winfsp) and [winfstest](https://github.com/billziss-gh/secfs.test/tree/master/winfstest). I am surprised that WinFsp fails winfstest, because to my knowledge it passes all of them. It also passes a new test suite (winfsp-tests) and Microsoft's own IfsTest.

Can you please point me to the failing tests in winfstest?

**Comment by bailey27** [comment]
@billziss-gh I installed the WinFsp release that I downloaded on May 3rd.  Then I built the passthrough sample program.

I am starting passthrough like this

```
C:\WinFsp\samples\passthrough\build\Release>passthrough-x64.exe -p c:\tmp\WinFsp -m X:
passthrough -p c:\tmp\WinFsp -m X:
The service passthrough has been started.
```

I got the winfstest I am using from here  https://github.com/dimov-cz/winfstest

The developer says it's base on your work.  

I think I found out about this version of winfstest from Dokany, which is why I am using it.

If I run that winfstest like this

```
run-winfstest.bat . x:\
```

then this is the output

```
C:\winfstest\TestSuite>run-winfstest.bat . x:\
C:\winfstest\TestSuite\\.\t\base\00.t . ok
C:\winfstest\TestSuite\\.\t\base\01.t . ok
C:\winfstest\TestSuite\\.\t\base\02.t .
not ok 2 - expect "CreateDirectory x:\\856b27a8 0" ERROR_ALREADY_EXISTS - got ERROR_FILE_EXISTS
not ok 6 - expect "CreateDirectory x:\\856b27a8 0" ERROR_ALREADY_EXISTS - got ERROR_FILE_EXISTS
not ok 2/10
C:\winfstest\TestSuite\\.\t\base\03.t . ok
C:\winfstest\TestSuite\\.\t\base\04.t . ok
C:\winfstest\TestSuite\\.\t\base\05.t . ok
C:\winfstest\TestSuite\\.\t\base\06.t . ok
C:\winfstest\TestSuite\\.\t\base\07.t . ok
C:\winfstest\TestSuite\\.\t\base\08.t . ok
C:\winfstest\TestSuite\\.\t\base\09.t .
not ok 6 - expect "CreateFile x:\\a334b9c0 GENERIC_WRITE FILE_SHARE_WRITE 0 OPEN_EXISTING 0 0" ERROR_SHARING_VIOLATION - got 0
not ok 8 - expect "CreateFile x:\\a334b9c0 DELETE FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0" ERROR_SHARING_VIOLATION - got 0
not ok 9 - expect "CreateFile x:\\a334b9c0 DELETE FILE_SHARE_WRITE 0 OPEN_EXISTING 0 0" ERROR_SHARING_VIOLATION - got 0
not ok 10 - expect_task "CreateFile x:\\a334b9c0 GENERIC_READ FILE_SHARE_WRITE 0 CREATE_ALWAYS FILE_ATTRIBUTE_NORMAL 0" 0 - got ERROR_ACCESS_DENIED
not ok 11 - expect "CreateFile x:\\a334b9c0 GENERIC_WRITE FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0" ERROR_SHARING_VIOLATION - got 0
not ok 12 - expect "CreateFile x:\\a334b9c0 DELETE FILE_SHARE_WRITE 0 OPEN_EXISTING 0 0" ERROR_SHARING_VIOLATION - got 0
not ok 14 - expect_task "CreateFile x:\\a334b9c0 DELETE FILE_SHARE_DELETE 0 CREATE_ALWAYS FILE_ATTRIBUTE_NORMAL 0" 0 - got ERROR_ACCESS_DENIED
not ok 7/19
C:\winfstest\TestSuite\\.\t\base\10.t .
not ok 10 - expect "DeleteFile x:\\d8c4fbf5" 0 - got ERROR_ACCESS_DENIED
not ok 11 - expect "CreateDirectory x:\\d8c4fbf5 D:P(A;;GA;;;WD)" 0 - got ERROR_FILE_EXISTS
not ok 12 - expect "GetFileSecurity x:\\d8c4fbf5 DACL_SECURITY_INFORMATION" 0 - got ERROR_ACCESS_DENIED
not ok 13 - expect "SetFileSecurity x:\\d8c4fbf5 DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)(A;;GR;;;SY)" 0 - got ERROR_ACCESS_DENIED
not ok 14 - expect "GetFileSecurity x:\\d8c4fbf5 DACL_SECURITY_INFORMATION" 0 - got ERROR_ACCESS_DENIED
not ok 15 - expect "RemoveDirectory x:\\d8c4fbf5" 0 - got ERROR_ACCESS_DENIED
not ok 6/15
C:\winfstest\TestSuite\\.\t-streams\streams\00.t
Command '['C:\\Python27\\python.exe', 'C:\\winfstest\\TestSuite\\\\.\\t-streams\\streams\\00.t', 'x:\\']' returned non-zero exit status 1
not ok 1 - expect "CreateFile x:\\32a6fc65:foo GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" 0 - got ERROR_INVALID_NAME
not ok 2 - expect "CreateFile x:\\32a6fc65 GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" ERROR_FILE_EXISTS - got 0
not ok 3 - expect "CreateFile x:\\32a6fc65:foo GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" ERROR_FILE_EXISTS - got ERROR_INVALID_NAME
ok 4 - expect "GetFileInformation x:\\32a6fc65" 0 -
not ok 5 - expect "GetFileInformation x:\\32a6fc65:foo" 0 - got ERROR_INVALID_NAME
Traceback (most recent call last):
  File "C:\winfstest\TestSuite\\.\t-streams\streams\00.t", line 15, in <module>
    testeval(r[0]["FileIndex"] == s[0]["FileIndex"])
IndexError: list index out of range
```

**Comment by billziss-gh** [comment]
Please do not use the passthrough file system for testing. The passthrough file system is a minimal file system that was written as an example to accompany a tutorial and does not correctly support most features.

For example, the passthrough file system does not support named streams, because they would complicate the tutorial. As another example, file security on files cannot be made to work in a passthrough manner, because the file system under passthrough (NTFS) does not allow arbitrarily setting security descriptors on files for all users.

There are ways around some of these problems, but again my goal with passthrough was to produce an easy to understand file system rather than one that passes all tests.

The reference file system in WinFsp is memfs (and its new .NET variant memfs-dotnet). These file systems aim for parity with NTFS, including implementing weird NTFS quirks in order to pass Microsoft's IfsTest. I have here the full [NTFS compatibility](https://github.com/billziss-gh/winfsp/wiki/NTFS-Compatibility) document.

Please consider retesting winfstest against memfs.

Here is an example run of winfstests over memfs. First run memfs:

```
C:\Program Files (x86)\WinFsp\bin>memfs-x64.exe -t -1 -i -F NTFS -m Y:
memfs -t -1 -n 1024 -s 16777216 -m Y:
The service memfs has been started.
```

And then winfstest:

```
Y:\>c:run-winfstest
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\00.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\01.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\02.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\03.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\04.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\05.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\06.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\07.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\08.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\09.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\base\10.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\reparse\00.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\reparse\01.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\reparse\02.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\reparse\03.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\streams\00.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\streams\01.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\streams\02.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\streams\03.t  ok
C:\Users\billziss\Projects\winfsp\ext\test\winfstest\t\streams\04.t  ok

total ................................. ok 733/733
```

**Comment by bailey27** [comment]
@billziss-gh 

As I understand it, memfs operates on a filesystem created in memory, while passthrough operates similarly to Dokany mirror.

I used passthrough to test the performance of winfsp vs Dokany because I thought that was an apples to apples comparison.

passthrough is over 2x faster than Dokany mirror in my tests.  cppcryptfs performs about the same as Dokany mirror if AES-NI can be used.

I agree that winfsp is definitely faster than Dokany.  I also think it is probably more stable.  I haven't had any stability problems with Dokany in a long time, though.

cppcryptfs, like Dokany mirror, cannot handle every file security operation if it is not being run as administrator.  I normally run cppcyrptfs not as administrator, and I have not found this to be a problem in my use of it. 

I would like for cppcryptfs to be faster, but for my usage, it is already fast enough.

I might look at porting it to use winfsp instead of Dokany in the future.

**Comment by billziss-gh** [comment]
@bailey27 thanks for your message.

> cppcryptfs, like Dokany mirror, cannot handle every file security operation if it is not being run as administrator. I normally run cppcyrptfs not as administrator, and I have not found this to be a problem in my use of it.

I understand the problem. I also often enable the backup and restore privileges on file systems that use NTFS as the underlying file storage.

> passthrough is over 2x faster than Dokany mirror in my tests. cppcryptfs performs about the same as Dokany mirror if AES-NI can be used.

Passthrough could be made faster if I actually invested more time in it. It currently is more of a demonstration on how to write a file system using WinFsp/Windows and does not care as much about complete file system correctness or performance.

For example, passthrough could be modified to properly use the NTOS cache manager (it currently does not). [The cache manager gets enabled when the file system gets initialized with [`FileInfoTimeout==-1`](https://github.com/billziss-gh/winfsp/blob/v1.0/inc/winfsp/fsctl.h#L136).] The cache manager would make the passthrough file system reach read/write speeds comparable to NTFS itself or about 9-10x times faster than Dokany for cached read/writes. [The reason that NTFS is fast is because of the cache manager and not because disk accesses are fast.]

The reason that I have not modified the current passthrough file system to use the cache manager is because the cache manager keeps files open for long times, which can interfere with file sharing, pending deletes, etc. on an NTFS file system. These problems show through because passthrough has a very simple design, but the design could be modified to avoid the problems. I can discuss this further if you are interested.

> I might look into porting cppcryptfs to use winfsp instead of Dokany in the future.

If you ever decide to go ahead with a port you can count on my support. Just ping me.

**Comment by benrubson** [comment]
> I might look into porting cppcryptfs to use winfsp instead of Dokany in the future.

Hi @bailey27, any news regarding WinFsp support ?
Many thanks 👍

**Comment by bailey27** [comment]
I'm sorry, but I don't see a change from using Dokany to WinFsp happening any time soon.

I'm much more busy now than I was before, and I don't have time to work on it.
