### ISSUE TITLE
Crash when reverse mount a entire disk

### ISSUE THREAD

**Issue by isleon** [bailey27/cppcryptfs#142]
Floders are fine, but when I try to mount a entire disk, I get a mounted disk with only total 1 GB space and it crashs when I open the subfolders, sometime crash just when open the mounted disk.

I have tested on Win7 and Win 10, SSD and HDD, it all gets the same error.

**Comment by bailey27** [comment]
Thanks for reporting this.

I wasn't able to reproduce the crash, but I do see the problem with GetDiskSpaceEx() when the root of the encrypted (in this case reverse) fs is the whole drive.  When I store the root of the fs, I make sure there's no trailing backslash. When I call GetDiskFreeSpaceEx with a path that is essentially "c:" then it fails, and returns an error.  I think the 1GB is some default that gets substituted upstream of my code.  If I add the trailing backslash before the call to GetDiskFreeSpaceEx if the path ends in ":", then it succeeds and the correct space is reported.

Here's a test build.  It's signed only by me and not co-signed by Encedo Limited using their extended validation certificate.  So you might get a Windows Smart Screen warning about it.  In that case you'll need to click on "More Info" and then "Run anyway" to run it.

Please let me know if the test build solves the problem
[cppcryptfs_1.4.3.10_test_for_isleon.zip](https://github.com/bailey27/cppcryptfs/files/7656286/cppcryptfs_1.4.3.10_test_for_isleon.zip)
.

**Comment by isleon** [comment]
Hi @bailey27, thank you for your great work.

Yes, I have tried the test build and it did worked, now I can get the correct disk space but the crash issue remains.

I found this might be a proformance issue. The disk I tried to reverse mount contains more than 70 thousand files, it will crash typically when I select all the files/folders in the root dictionary and try to get the total file size or to get a tree view. It seems the program fail to handle too many files at once.

I have test with a disk with less files like only 3 thousand and it worked perfectly, no crash. Please let me konw if there are any information or logs somewhere I can share with you to help to locate the problem.

Btw, I use the reverse mode to backup the file to cloud, it is getting hard to locate and download the only files I need as all the filename been encrypted, just wonder how you guys find the exact file you need in the cloud instead just not encrypt the filename. I can't mount the cloud as a local drive since the provider have limited such usage so is there any way to create a list with both original and encrypted filename accordingly?

**Comment by bailey27** [comment]
I reverse mounted a whole external HDD with over 60,000 files and selected all the files/folders in the root directory and did "properties" and it didn't crash.



For seeing the unencrypted names there is cppcryptfsctl -l

e.g.

```
C:\tmp>cppcryptfsctl -lk:\
gocryptfs.conf => .gocryptfs.reverse.conf
gocryptfs.diriv => gocryptfs.diriv
s-6gGkYz23oWWBlXgdpD0Q => one

C:\tmp>cppcryptfsctl -lk:\s-6gGkYz23oWWBlXgdpD0Q
. => .
.. => ..
b0ETxpSF-FmunPL8YFpDyg => a.txt
cDn172LeAJX3ZP0s9rZVOw => b.txt
gocryptfs.diriv => gocryptfs.diriv
-tGMqHRTyXP1ZIvLxH-oTg => c.txt
```

Unfortunately, it does not recurse.

I built cppcryptfs with logging, both a release build and debug one.  The only difference is compiler optimizations are off in the debug one.  

You need to make a directory c:\cppcryptfslogs and it will put the logs there.

Another thing we could try is generating a crash dump.

The crash dump will enable me to see where in the code cppcryptfs was when it crashed.

I cannot make ANY PROMISES about what sort of SENSITIVE INFORMATION might end up in the crash dump.

If you get this tool https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

Then you can do this (in an administrator cmd prompt)
```
md c:\dumps

procdump64 -ma -i c:\dumps
```

Then, when cppcryptfs crashes, procdump should generate a file like

cppcryptfs.exe_200927_114204.dmp

in c:\dumps.

The file will be about 150MB. 7-Zip can compress it down to around 30MB, but it will still be too big to attach to gmail. You could use 7-zip to split it into a couple of files and attach them to separate emails.  You can find my gmail address if you look at the digital signature cppcryptfs.exe.  It has my name in it.

You MUST use the cppcryptfs.exe in one of the zip files attached to this post (not the previous one) because I saved the debug symbols for those.

Also, at least in my setup, procdump causes two .dmp files to be created on each crash. If this happens, I should be able to use either of them (shouldn't need both).

Here's a version with logging you can try.  

[cppcryptfs_1.4.3.10_test_for_isleon_with_logging.zip](https://github.com/bailey27/cppcryptfs/files/7699024/cppcryptfs_1.4.3.10_test_for_isleon_with_logging.zip)

The same built for debug.

[cppcryptfs_1.4.3.10_test_for_isleon_with_logging_debug.zip](https://github.com/bailey27/cppcryptfs/files/7699064/cppcryptfs_1.4.3.10_test_for_isleon_with_logging_debug.zip)

If you want to try the crash dump, It will be better if you can make it happen with the debug one.  It's easier to see what happened with a debug build.

**Comment by isleon** [comment]
Thank you so much for your help.

I have tried both the logging and debug version of build and generated both logs and dumps.

By every crash it will produce 3 dump files and the build with logging also produce dumps so I renamed the dumps and logs to let you know which dumps or logs come from which build.

As the logs and dumps are almost 500MB, and it is just a bunch of test random file no need worry for privacy so I'm gonna just up it on mediafire and post the link below:

[https://www.mediafire.com/file/x90xreaoqbvbmq4/log_and_dumps.zip/file](url)

**Comment by bailey27** [comment]
Thanks for providing these files.   They really helped.

I think I found the problem.

The crash seems to be because there is a really long file name, but you don't have long filenames enabled for the filesystem.

I am not handling this situation properly with a reverse filesystem.

I think if you enable long file names when you create your reverse file system, then it will not crash.

**Comment by isleon** [comment]
Yes, it worked like a charm after I enabled long file names.

Thank you so much for your help.
