### ISSUE TITLE
How to use cppcryptfsctl with --list?

### ISSUE THREAD

**Issue by null-python** [bailey27/cppcryptfs#143]
Hi, can you show an example of using cppcryptfsctl with the --list command when cppcryptfs is running in the background?

**Comment by bailey27** [comment]
Here's an example.  I think maybe this getopt library I'm using is non-standard in that it requires and equal sign after the long options if there is an argument for the option.  

```
C:\>cppcryptfsctl --list
A:
B:
D:
E:
F:
G:
H:
I:
J:
K: c:\tmp\test
L:
M:
N:
O:
P:
Q:
R:
S:
T:
U:
V:
W:
X:
Y:

C:\>cppcryptfsctl --list=k:\
.dropbox.device => RhfiidgW_ZcByIV27cZEpQ
openssl-1.1.1l => bYzX8h9p7nEM5whwWHrGXg

C:\>cppcryptfsctl --list=k:\openssl-1.1.1l
. => .
.. => ..
ACKNOWLEDGEMENTS => pXddvfFKefA0R0PWzpwKA0_h3h2WRMhLIu5fA8wwLsA
apps => YHh4YGrzyvVf7Pp6Kr1LvA
appveyor.yml => ZMTqEzHLka50n3ZfTop8ug
AUTHORS => sDqWDM2oX8xnSXXOABc9zw
build.info => KogF63IOi3azTH9mFx3zxQ
CHANGES => zFhl87kR12qzgOhHGEzt_w
config => xDo8LdeFWNPOBYDh1oUBHQ
config.com => EKGk70fJpouydWcolTrnmA
Configurations => CZ1KjzcI2dDiEk-S9dpmNw
Configure => cQRR_ny5E2ufSM_rsZL_Tw
CONTRIBUTING => Amf3AxZ38dxG9_TzN0a4qA
crypto => DREI2DlHhx9Pway-jt8qGg
demos => sxdFC4tuzj0Fj7shcBD1Zw
doc => sNDc2BxQUcx3i6qDcQiNvg
e_os.h => N-xYIfuGXo81rjhCf1uw7g
engines => a5xd3eJz1_YJbQiK_jIYxg
external => ybiSSm3WASCgRxHWJ_0LjQ
FAQ => __BxYRS82vgavbME7qRiLQ
fuzz => oS6PkAya9ib4nBG86i0kKQ
include => PX-dbQbrhpbGliNLQf2tMw
INSTALL => PfAcwENz48KOmXp4lYVudg
LICENSE => VwOkjT6pi9LuPEjFIj0lUQ
ms => WNUOkGUDJQKvYdBfyIQcVg
NEWS => SCW6m9pmrca25l11-0R9Ag
NOTES.ANDROID => iHCH03OjajSnsrvdUY7ZSQ
NOTES.DJGPP => VrMDwf0gTF1g0nOWRhx6Dw
NOTES.PERL => qrAWTsWn5wUm-nX-t5TzKg
NOTES.UNIX => RrVGFr_Bp53Efy5NUWOH1A
NOTES.VMS => xxQ_8YRvLYMWhyz4rEuYqQ
NOTES.WIN => Ln1cqchGsDlIC2o31e5uMQ
os-dep => UT0umyMlbUGsL_8SmZ6sYg
README => KnDbXdYx0cK_cww2YSskGg
README.ENGINE => 1s8V9-c7MSPBElHKQbiHVw
README.FIPS => mwPFb-bgnH7r6asEnQ82IA
ssl => CJqTtPn1RxyXGyPYFCaf2A
test => ggCye714EPrFkHR1BSKbqQ
tools => wiwSGjDE3-VdVOIP7e2LdQ
util => 4WwZYBCWEntEOIC-WnT7wA
VMS => nm64-YbprcG7DWU0Eorm9Q
```

**Comment by null-python** [comment]
I'm getting this error

![image](https://user-images.githubusercontent.com/16840836/147371490-6150f5af-214f-460d-8bea-dd8d45186a90.png)

Do you know why? cppcryptfs gui is running in the background

**Comment by bailey27** [comment]
Please make sure both cppcryptfs and cppcryptfsctrl are either both running as administrator or both not running as administrator.  For cppcryptfsctl, that's controlled by whether or not the cmd console window it's run from is run as administrator or not.

However, I think this problem is maybe happening because you are running cppcryptfsctrl and cppcryptfs from with different versions.  When I added the deny other sessions type stuff, I changed the name of the named pipe to be decorated with the session id.  Could you make sure cppcryptfs and cppcryptfsctl have the same version?

You can get the version of cppcryptfsctrl by passing -I -v to it, e.g.
```
cppcryptfsctl -I -v
```

The cppcryptfs version is the about tab.

**Comment by null-python** [comment]
Thanks, the problem was that the version numbers were different
