### ISSUE TITLE
Folder mount point persists as a link after dismount

### ISSUE THREAD

**Issue by psisis** [bailey27/cppcryptfs#153]
When mounting a fs to a folder mount point, it links this folder to the actual decrypted volume. When dismounting, the folder stays as an inaccessable symbolic link with type (per Win Explorer) “Mounted Volume”. Or as `dir` says: `mountfolder-> Volume{xx-xx-xx-xx-xx}\`. This makes it impossible to remount the fs without first deleting and creating a new mount point folder.

Windows acknowledges this as an empty dir so this could be scripted. But maybe a feature could be to automatically remove and recreate mount points folders or ignore dead links on a non-fuse level.

**Comment by bailey27** [comment]
It seems to happen only if I don't run cppcryptfs as administrator. If I run as administrator, then I can re-mount without deleting and re-creating the empty dir.

I'll add a feature to automatically do the deleting and re-creating if necessary.

**Comment by psisis** [comment]
Well, it seems I still have some issues with automation. A Windows Logoff script dismounting rather than Shutdown requires user-permissions. I’d appreciate a solution in a future commit or release.

**Comment by mhogomchungu** [comment]
I solved this problem by deleting and then recreating the mount point after unmounting.

https://github.com/mhogomchungu/sirikali/blob/59ef2ef591cc111cec31d1abb77ad99061ca986a/src/sirikali_cppcryptfs/main.cpp#L393-L398

**Comment by psisis** [comment]
@mhogomchungu Yes, I also believe it can be classified as a bug. Even by letting cppcryptfs (which is elevated) dismount by itself at shutdown will not make a clean dismount.

I’d like to try a fix, but seems you‘re not using any “upstream” source code?

**Comment by san-r** [comment]
> I think this is a bug because you start with a normal folder and after unmounting, you are left with a "broken" folder and the only way to fix it is to manually delete it and recreate it.
> 
> I solved this problem by deleting and then recreating the mount point after unmounting.
> 
> https://github.com/mhogomchungu/sirikali/blob/59ef2ef591cc111cec31d1abb77ad99061ca986a/src/sirikali_cppcryptfs/main.cpp#L393-L398

Great! Thanks for solving this problem. When can we download the new windows binaries?

**Comment by bailey27** [comment]
I don't know why, but the directory, after it is mounted, becomes a a Junction (like a symlink), and it remains so after being unmounted.

When it is in this state, the standard ways of checking if it is an empty directory fail.  E.g. PathIsDirectoryEmpty return FALSE, and FindFirstFile doesn't work normally either.

However, it will still work if  I try to mount to it anyway.

It can be determined to be like this (empty, but now a Junction and usable for mounting)  if PathIsDirectory returns TRUE and FindFirstFile fails with ERROR_PATH_NOT_FOUND or ERROR_NO_SUCH_DEVICE.

The behavior appears to be consistent. 

The check for NTFS still succeeds after that.

I think it's better to modify the check for emptiness when mounting rather than to delete and re-create the directory.

I hope to have build with the fix up shortly.

**Comment by bailey27** [comment]
The latest release 1.4.3.12 fixes this.
