### ISSUE TITLE
Reverse mode fileystems are always mounted read-only

### ISSUE THREAD

**Issue by Wihlelm** [bailey27/cppcryptfs#23]
Hi bailey27,

first of all, thank you for your port of gocryptfs in windows.

Can you explain why reverse mode fileystems are always mounted read-only ? For backup it is perfectly fine, but what about synchronization with a sync client ? For example two different computers where files are stored unencrypted which sync through a cloud where files are stored encrypted ? Any modification on one side should propagate to the other. Moreover, most of sync clients needs to have write access to store a local journal of the sync process inside the sync directory.

Is it inherent to the program ? Is it not possible to allow to bypass this default option of read-only to give write access ?

Best regards

**Comment by Nodens-** [comment]
This is a gocryptfs limitation. Currently there is no support for RW reverse and with the current AES-SIV implementation even if there was support for writes, you would not be able to sync files with it since the encryption is non-deterministic.

See here: https://github.com/rfjakob/gocryptfs/issues/108

**Comment by bailey27** [comment]
@Wihlelm , if gocryptfs implements RW in reverse mode, then I'll implement it in cppcryptfs.

**Comment by Wihlelm** [comment]
Thanks bailey, it would really be great to have such an option. By now I will keep encfs which provide RW support for reverse mode, even if I know that it has some security holes.
