### ISSUE TITLE
potential resource leaking

### ISSUE THREAD

**Issue by mhogomchungu** [bailey27/cppcryptfs#24]
Below code range will leak file resource if taken code path return early. Memory leak will occur too if the condition at line 426 is found to be true.

Looking around this function and other functions in your project and i did not see why you are not using ```std::unique_ptr``` to handle pointer based resources and not using ```std::vector<char>``` to handle your character buffers or an RAII pattern to handle to automatically call ```DeleteFile``` on function exit.

https://github.com/bailey27/cppcryptfs/blob/51c04c863eabfe27b53af7258035460137fcf676/cppcryptfs/config/cryptconfig.cpp#L405-L435

In this[1] function for example, i think ```RegCloseKey(hk_pws);``` call should be handled automatically by C++ using RAII pattern.

[1] https://github.com/bailey27/cppcryptfs/blob/51c04c863eabfe27b53af7258035460137fcf676/cppcryptfs/util/savedpasswords.cpp#L38

**Comment by mhogomchungu** [comment]
In the below code range, a memory leak will occur is the condition at line 426 is found to be true.

https://github.com/bailey27/cppcryptfs/blob/51c04c863eabfe27b53af7258035460137fcf676/cppcryptfs/config/cryptconfig.cpp#L416-L435

**Comment by bailey27** [comment]
@mhogomchungu ,

Thank you for pointing out the potential memory leak.

In write_volume_name(), I should not be returning from inside the try.  I normally don't do that, because I normally want to use the catch to set an error return value and free resources after the catch block.

In this particular case, the error condition on line 426 is extremely unlikely to happen, and the code is called only when the fs is unmounted and only if the user has changed the volume name.

It will be fixed in the next release.

I started coding cppcryptfs after a long hiatus from C++ programming.  I wrote most of the code before I started learning the new features from c++11.  That is why you see c++11 features used in some places but not in other places where it would be desirable to use them.

I agree that I should have used the RAII pattern more and there are many places where std::vector should have been used instead of a raw buffer and also many places where std::unique_ptr would have been useful.

**Comment by mhogomchungu** [comment]
I suspected that returning early with return statement was probably a lapse of some sort since your code pattern seems to be returning early by throwing.

If you are using C++14, a function that i use to manage pointer based resource with std::unique_ptr is here[1]. It should be easy to write a custom function that returns a FILE handle for the function to manage. It should be easy to modify the function to be C++11. Let me know if you want to use it and want it to be customized for your particular case and i will make a pull request with the necessary changes.

[1] https://github.com/mhogomchungu/sirikali/blob/8ffae0f32e69657987c484683ce1b3b62e160e21/src/utility2.h#L53-L70

**Comment by bailey27** [comment]
Yes, I can used C++14.  I would like for you to make a pull request with your changes please.

**Comment by mhogomchungu** [comment]
My fork of your repository is here[1] and i have made these[2] changes so far.

[1] https://github.com/mhogomchungu/cppcryptfs

[2] https://github.com/mhogomchungu/cppcryptfs/commits/master

any comments?

**Comment by bailey27** [comment]
Pull request merged.  Thank you!
