### ISSUE TITLE
Mounting UNC path fails, local path OK

### ISSUE THREAD

**Issue by heikoh81** [bailey27/cppcryptfs#30]
Hi there,

I'm testing cppcryptfs as a replacement for EncFSMP.
I have a NAS on my LAN that I can access with Windows Explorer:
\\192.168.178.178.202\gocryptTEST
This samba folder is password protected, however, I open this folder in Windows Explorer first (entering credentials) before the following steps.

cppcryptfs can create an encrypted folder in this path (2 files are being created upon this, so write access seems to be granted correctly).

If I try to mount my newly created folder, cppcryptfs tells me that there is no conf file in this directory (alhtough I can see it there). Thus I cannot access the encrypted folder.

However, if I connect the network share first in Windows Explorer (assigning a drive letter in Windows), I now can mount the encrypted NAS folder with cppcryptfs.

Why can't I use the UNC-path directly? Or am I the only one having this problem?
Would be much more convenient to use UNC directly in cppcryptfs.

**Comment by bailey27** [comment]
I prepend \\?\ to the path so that the Windows MAX_PATH 259 character path limit can be overcome.

But if the path is UNC, then I should prepend \\?\UNC\ to the path instead.

I put this fix in release 1.4.0.17 which I just now uploaded.

I tested it using a UNC path from my server, and it worked for me.

Please try it and let me know if it fixes the problem for you.

**Comment by heikoh81** [comment]
Thank you for the fix, I can now mount my UNC-path directly within cppcryptfs with release 1.4.0.17.
