### ISSUE TITLE
Some apps hangs the container

### ISSUE THREAD

**Issue by nevubm** [bailey27/cppcryptfs#42]
Extract this zip https://download.xnview.com/XnViewMP-win-x64.zip into new encrypted container and execute xnviewmp.exe

The app doesn't start for a very long time and everything else accessing files in the volume hangs. But if you let it run overnight, it will eventually start and then everything works again.

**Comment by bailey27** [comment]
I tried it and got very different (but still wrong) behavior.

If I try to run xnviewmp.exe without extracting the zip, then it won't run because none of the many dlls it needs are there.

If I do extract all and run it from the folder that it and all its dlls are in, then it runs OK about 1 in 5 tries.

The other 4 out of 5 tries, either it doesn't run with no error message, or I get a Windows error dialog.

In the error dialog, I've seen 0xC000009A (STATUS_INSUFFICIENT_RESOURCES), 0xC0000006 (STATUS_IN_PAGE_ERROR), and 0xC000012F (STATUS_INVALID_IMAGE_NOT_MZ),  sometimes with messages like this screen shot

![image](https://user-images.githubusercontent.com/17813578/49342702-7ebb5400-f62c-11e8-94ec-6f6262595bf9.png)

or like this

![image](https://user-images.githubusercontent.com/17813578/49343068-5f72f580-f631-11e8-8d59-3d9b0ddb80da.png)


I have almost the same behavior when trying this with Dokany mirror, except I've yet to see a 0xC0000006) when running with Dokany mirror.

Mirror is Dokany's reference passthrough filesystem upon which the part of cppcryptfs that interfaces with Dokany is based.

I am pretty sure this is a Dokany problem.  I bet it has to do with memory-mapped i/o (paging i/o).

The way to run mirror is top open a cmd window and cd to

C:\Program Files\Dokan\Dokan Library-1.2.0\sample\mirror

And run 

mirror /r c:\tmp\mirror /l m

Running it from an administrator command prompt doesn't seem to make a difference.

Could you try it with mirror and let me know if the behavior is any different for you?

**Comment by mesvam** [comment]
I couldn't run mirror as user, only as admin. Doing this same test in a mirrored dir I get the exact same symptoms, so you're right, it's a Dokany thing.

I've also found that increasing filesystem threads to the maximum 14 helps a bit and lets it launch within a minute.

And just for reference, I was running:
Windows 7 SP1 x64
Dokany 1.1.0.2000 x64
cppcryptfs 1.4.0.17

After updating Dokany and cppcryptfs to latest versions (1.2.0.1000 and 1.4.0.22 respectively) I still get the same symptoms

**Comment by samokhodkin** [comment]
Hi, I just checked it out. Started mirror exe as `mirror /r d:\tmp\tmpdisk /l h: /t 3 /s 2> log.txt`, 
extracted the XnViewMP-win-x64.zip to disk H:,  launched the xnviewmp.exe for few times.

Didn't meet a single problem, it works perfectly.

The system is the same as in the referenced dokany issue.

**Comment by nevubm** [comment]
Closing and reopening the app is fast for me. I'm guessing because of caching. Maybe you have to clear the cache or remount as a different drive letter to prevent that?

Definitely using Windows 7, and I also didn't find `MaxLoaderThreads` anywhere in the registry.
Currently for me on Win7:
```
> dokanctl /v
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl : Aug  9 2018 15:10:31
Dokan version : 120
Dokan driver version : 0x190
```

**Comment by nevubm** [comment]
Ok, this is weird. I can't reproduce this anymore. And neither clearing the cache nor remount to different drive produces bad behavior.

**Comment by gyurmogyuri** [comment]
Yes, I can see. Some of application is not running from container. For me games and bluestacks

**Comment by bailey27** [comment]
The fix I made for issue #49 seems to fix XnViewMP as well.  I launched it ten times in a row from a container without any problems.  Please let me know if you still have an issue.

**Comment by nevubm** [comment]
I still encounter this periodically, but it's not consistent.

**Comment by nevubm** [comment]
I now suspect that the issue may have been related to Kaspersky Antivirus, since the issue goes away after uninstall. Simply disabling it doesn't help.

So for others as a workaround, perhaps try uninstalling any antivirus or other drivers that can affect disk I/O.
