### ISSUE TITLE
Acrobat Reader DC

### ISSUE THREAD

**Issue by ssemke** [bailey27/cppcryptfs#44]
Acrobat Reader DC is denied permission to open a PDF file on a cppcryptfs drive:
cppcryptfs 1.4.0.22
Dokan Library 1.2.1.2000
Acrobat Reader DC  2019.0.10.20069

Under Reader's "Edit/Preferences/Security (Enhanced)/Sandbox Protections" setting, turning off "Run in AppContainer (Beta)" permits file access.  Turning the setting back on results in denied permission.

This behaviour is consistent with cryptomator, which also uses dokany.

I do not experience the issue when using securefs-win which uses winfsp rather than dokany.

I think you raised the issue with dokany's developer, https://github.com/dokan-dev/dokany/issues/640.  Did you get a resolution?

**Comment by bailey27** [comment]
That dokany issue #640 was about something else.  It was from when I was trying to use imperonsonation (run cppcrypts as aministrator but impersonate the logged in user, or rather, whichever use the original i/o request came from).  In that case, enabling the AR protected mode wasn't working.  I never figured out why.

In your case, you are using another option next that one "Run in AppContainer (Beta)".  I don't know why that doesn't work.  I'd like to find out, but since it's not turned on by default in AR and I don't use it, I don't know when I'll get around to working on it.
