### ISSUE TITLE
[question] How works the setting case insensitive?

### ISSUE THREAD

**Issue by vcxy** [bailey27/cppcryptfs#58]
Hi,
I am impressed by the setting "case insensitiv".
I would be interested to know how these setting works exactly. Does the program additionally save all file names internally in capital letters or how did you implement this?
So far, I have found no loss of speed with this setting. Is this only noticeable with folders with thousands of files?

**Comment by bailey27** [comment]
Yes, that is sort of how it works.

If you you have case insensitive on, then cppcryptfs maintains a cache (using an unordered_map of  unordered_maps) that maps the upperrcased unencrypted filenames to the correct-case unencrypted filenames.  The first level map is for directories, and the second level maps are for the files and directories in those directories.

When you try to open a file, cppcryptfs converts the file path to uppercase and tries to find the directory and the file in the cache.  If it finds it, then it encrypts the correct-case path and tries to open that encrypted file name.

Each node of the cache contains mappings to all the filenames in a whole directory.

If a file is created or deleted, then it's corresponding entry in the cache is added or deleted.

If a file is not found in the cache, then if the cache node has timed out, then the whole directory is re-read and cached.  

If there wasn't a time-out, then it treats the miss as though the file isn't there.

The default timeout is 10 seconds.  The time out enables cppcryptfs to recognize new files when you are syncing the encrypted filesystem with a cloud service.

It keeps as many as 100 directories' worth of file names in the cache at one time.

The hit ratio is typically very high, but  a cache miss is very expensive because an entire directory needs to be enumerated.

I said that it would reduce performance because it must do so to some extent.  But the performance impact is very small in typical usage.  I haven't noticed any slowdown myself, but I've never actually benchmarked it.

**Comment by vcxy** [comment]
Thank you very much for the information
