### ISSUE TITLE
Symbolic link (windows 10)

### ISSUE THREAD

**Issue by gilles007-** [bailey27/cppcryptfs#75]
hello,
i'm using Symbolic links (mklink /D) on some folders in my computer.
I can create a Symbolic link from a folder on my C: drive to the mounted folder.
I can't create a Symbolic link from the mounted folder to the mounted folder.
But I can create a Symbolic link from the unencrypted folder to the unencrypted folder.
My problem is that I can't create a Symbolic link from the mounted folder to a folder on my C: drive.
I can create a Symbolic link from the unencrypted folder to a folder on my C: drive but i can't copy files.
Program is crashing.

**Comment by gilles007-** [comment]
To be more precise : I have a program installed in the mounted folder but I want to store 1 big folder on C: (unencrypted)

**Comment by bailey27** [comment]
I think the problem is that Dokany doesn't support symbolic links.  I tried with Dokany mirror.exe and could not make a symbolic link from outside the Donkany drive to a folder on the Dokany drive.

I was able to link from a directory on my cppcryptfs drive to a directory on my c: drive and copy files from it without crashing.
