### ISSUE TITLE
[Feature Request] gocryptfs.diriv

### ISSUE THREAD

**Issue by madburg** [bailey27/cppcryptfs#82]
Great work @Bailey27! I just made this a portable app (it was practical just about there on its own, besides the writing to the HKCU hive, now that is written to the portable app dir)

Question, while we can move the gocryptfs.conf out of the mounting dir path, if I move out the _gocryptfs.diriv_ from the mounting dir path, I can no longer write to the virtual mount point. So the request is can the _gocryptfs.diriv_ file be coded to reside elsewhere?

**Comment by bailey27** [comment]
No, there must be a diriv file in every directory that contains encrypted files if you are using encrypted file names.  

The design of gocryptfs is such that this file must exist in every directory for encrypted file names to work.

**Comment by madburg** [comment]
Ok, understood now. Can I enquire what data is written to that file when you have a moment?

**Comment by bailey27** [comment]
The gocryptfs.diriv file in each directory contains a pseudo-random 128-bit initialization vector that is used when encrypting the file names.  Both the encryption key and the directory's diriv are used when generating the encrypted file names and when decrypting them. This is so that two files with the same names but in different directories will have different encrypted file names.

**Comment by madburg** [comment]
Thanks Bailey27!
