### ISSUE TITLE
Windows Update doesn't work when cppcryptfs is used

### ISSUE THREAD

**Issue by dhardtke** [bailey27/cppcryptfs#93]
Hey,

here's a strange bug:

My Windows Update (and Windows Store installations) won't work when a vault is decrypted and mounted by cppryptfs.

All I get is error code 0x80070057.

The CBS.log contains

```
2020-03-05 22:21:46, Info                  CBS    Failed to internally open package. [HRESULT = 0x800f0805 - CBS_E_INVALID_PACKAGE]
2020-03-05 22:21:46, Info                  CBS    Failed to create open package. [HRESULT = 0x800f0805 - CBS_E_INVALID_PACKAGE]
2020-03-05 22:21:46, Info                  CBS    Failed to OpenPackage using worker session [HRESULT = 0x800f0805]
```

Took me a while to figure this out, maybe someone else stumbles upon this and finds it helpful.

Cheers.

**Comment by bailey27** [comment]
I have my filesystem mounted almost all the time, and I've rarely had a problem with Windows update.  I've never had any I could trace back to cppcryptfs.

I think there might be some interaction with Windows Update because I do sometimes get weird empty directories with MSI in the name and .tmp as the extension (the directory name has .tmp for the extension) in the root directory of my mounted cppcryptfs volume. 

But for me, Windows updates have always gone smoothly 99.5% of the time.

I just now installed the Netflix app from the Microsoft Store without any problems while my volume was mounted.  It didn't create a new MSIXXXXX.tmp folder.

**Comment by dhardtke** [comment]
Thanks. Maybe it has something to do with me getting an error message from cppcryptfs on startup:

![grafik](https://user-images.githubusercontent.com/1360135/77248999-56e76980-6c3e-11ea-89bb-d53f69df8824.png)

I do use a batch file that I start using the task scheduler when my PC is starting:

```
@echo off
start cppcryptfs.exe --tray
timeout /t 1 /nobreak >nul

:: change codepage for umlauts
chcp 1252>nul
cppcryptfs --saved-password --mount=C:\Users\user\Vaults\Finanzen --drive=A --tray --exit
cppcryptfs --saved-password --mount=C:\Users\user\Vaults\Archiv --drive="C:\Users\user\Decrypted Vaults\Archiv" --tray --exit
cppcryptfs --saved-password --mount=C:\Users\user\Vaults\Bewerbungen --drive="C:\Users\user\Decrypted Vaults\Bewerbungen" --tray --exit
cppcryptfs --saved-password --mount=C:\Users\user\Vaults\Verträge --drive="C:\Users\user\Decrypted Vaults\Verträge" --tray --exit
```

This strangely only mounts the vault `C:\Users\user\Vaults\Finanzen` to A:, but none of the other vaults are mounted.

`C:\Users\user\Vaults\Archiv` and `C:\Users\user\Vaults\Verträge` look like a shortcut, but I can't open them:

![grafik](https://user-images.githubusercontent.com/1360135/77249044-b6de1000-6c3e-11ea-9e7b-4aa913a268b9.png)

**Comment by Nodens-** [comment]
Pretty sure the MSIXXXXX.tmp directories come from bad MSI installers and not from WU interacting with cppcryptfs. They can end up on any mounted fs seen by windows.

**Comment by dhardtke** [comment]
Okay. I haven't seen any MSIXXXX.tmp directories when my Windows Update didn't work.

Apart from that, I still have the issue that my batch file only decrypts and mounts the first Vault and cppcryptfs exits with _Named pipe connection timed out_.

Afterwards, it leaves the other directories in a broken state (even after exiting cppcryptfs) - only a reboot helps:

![grafik](https://user-images.githubusercontent.com/1360135/77697936-0c544d00-6fb0-11ea-9f50-a4b497e3ff67.png)

**Comment by dhardtke** [comment]
Okay, I managed to fix my other issue. For some reason these folders were broken (maybe they were invalid sym- or hardlinks) and I could just delete them. Afterwards, cppcryptfs started working normally again.

I will close this issue but might reopen it if I encounter the Windows Update problem again.

**Comment by dhardtke** [comment]
@bailey27 Do you have any idea why the error

> Named pipe connection timed out.

would appear on startup?

My batch file is still as follows:

```batch
@echo off
start cppcryptfs.exe --tray
timeout /t 2 /nobreak >nul

:: change codepage for umlauts
chcp 1252>nul
cppcryptfs --saved-password --mount=C:\Users\nick\Synced\Finanzen --drive=A --tray --exit
cppcryptfs --saved-password --mount=C:\Users\nick\Synced\Archiv --drive="C:\Users\nick\Decrypted\Archiv" --tray --exit
cppcryptfs --saved-password --mount=C:\Users\nick\Synced\Bewerbungen --drive="C:\Users\nick\Decrypted\Bewerbungen" --tray --exit
cppcryptfs --saved-password --mount=C:\Users\nick\Synced\Verträge --drive="C:\Users\nick\Decrypted\Verträge" --tray --exit
```

**Comment by mustermann23** [comment]
I was facing the exact same issue and found out:
Windows Update will only break when you mount to drive letters A or B.

**Comment by dhardtke** [comment]
You're right: I have one folder mounted on A:

**Comment by bailey27** [comment]
Do you think I should remove A and B from the list of mountable drive letters?

I think the issue probably has something to do with their historical association with floppy drives.

**Comment by dhardtke** [comment]
I wouldn't mind actually since there's plenty of other letters to choose from.

**Comment by Nodens-** [comment]
> Do you think I should remove A and B from the list of mountable drive letters?

I would say no. Upon further testing on vm this manifests with anything mounting on A. I can replicate it with Daemon Tools mounting a vhd there. And I could also trigger it via mounting a network share. It is a WU issue and should be treated as such. Don't remove functionality for something that will probably be fixed at some point while no one notices hence the limitation will remain. It is nowhere mentioned in documentation that these drive letters are reserved. And if they were they could not be available int he first place.
Although floppy drives are rare these days, there are bound to be systems with them and will most likely have similar issues. My guess is that their installer is enumerating drive letters sequentially in order to create temporary files, or something even sillier like looking for bootloader/MBT/bootmanager/EFI partition without going through the proper route of checking BCD entries.

My suggestion is to just add a caveat to the documentation mentioning the WU bug existing at the date of writing.

**Comment by bailey27** [comment]
I've updated the documentation to point out this issue.
