### ISSUE TITLE
"error 0x5 access is denied"

### ISSUE THREAD

**Issue by TowerBR** [bailey27/cppcryptfs#96]
I'm getting "error 0x5 access is denied" in some files. These are files that I previously accessed without problems. I can access other files in the same volume without problems, it seems random, I did not identify any characteristics in common, both in the blocked or in the ones that open. I already checked properties, permissions, etc. These files are on an external hard drive. Any idea? (Win10)

**Comment by bailey27** [comment]
This sounds like a problem that I thought was fixed in Dokany 1.3.1.1000.

I was having the problem myself but it went away after I upgraded to Dokany 1.3.1.1000.

Are you using 1.3.1.1000?

The workaround to try is to open a cmd window and use the cppcryptfsctl -l command to get the path to the encrypted file, go to that file in file explorer and right click on it and do properties and then click the security tab and add yourself to the users who have full control of the file.

Then you should be able to access the file again.

**Comment by TowerBR** [comment]
> Are you using 1.3.1.1000?

Looks like 1.3.0 (`\Program Files\Dokan\Dokan Library-1.3.0\`)

How / where can i confirm the exact version?

> The workaround to try is (...) add yourself to the users who have full control of the file.

I already tried it and it didn't work. At the moment, I recovered the - few - files from a backup and overwrote the files inside the container, and everything was ok. I'll keep watching.

**Comment by bailey27** [comment]
Yeah, you must have Dokany 1.3.0 installed.

I have this
```
C:\Program Files\Dokan\Dokan Library-1.3.1
```

Also, you can check it on the About tab in cppcryptfs

I would upgrade to Dokany 1.3.1.1000 and see if it happens again

https://github.com/dokan-dev/dokany/releases

**Comment by bailey27** [comment]
Are you still having this problem?
